[static_conf]
cloud_base_url = "http://192.168.0.4:8080" # IP de tu PC/Servidor donde corre gsu_sentinel_cloud
turbine_token = "TURBINA_NORT_01"

[static_conf.network]
zmq_endpoint = "tcp://127.0.0.1:5555" # IP de la cámara térmica
mqtt_broker = "127.0.0.1"             # Broker MQTT (ej. Mosquitto)
mqtt_port = 1883

[initial_dynamic]
max_temp_trigger = 55.0  # Si sube de 55, alerta
scan_wait_time_sec = 5   # Espera 5s en los bordes
system_enabled = true
pan_step_degrees = 0.5   # Velocidad del barrido