[static_conf]
# AQUÍ ESTÁ LA CORRECCIÓN DE LA IP
cloud_base_url = "http://209.94.60.160:8080" 
turbine_token = "GSU_TR_01"

[static_conf.network]
zmq_endpoint = "tcp://127.0.0.1:5555"
mqtt_broker = "127.0.0.1"
mqtt_port = 1883

[initial_dynamic]
max_temp_trigger = 55.0
scan_wait_time_sec = 5
system_enabled = true
pan_step_degrees = 0.4
