

# --- Configuración General ---
# URL donde está corriendo tu servidor gsu_sentinel_cloud
# Si estás probando localmente, usa http://127.0.0.1:8080
# Si es remoto, pon la IP pública del servidor.
cloud_url = "http://192.168.0.6:8080"

# Identificador único de este dispositivo para la nube
turbine_token = "turbine_104_park_15"

# --- Límites de Control y Ciencia ---
[limits]
# Temperatura (Celsius) que activa el modo "Tracking" (Seguimiento)
max_temp_trigger = 50.0 

# Segundos que la cámara se quedará grabando datos científicos una vez centre el objetivo
collection_duration_sec = 10

# --- Configuración de Red ---
[network]
# Donde escucha el Thermal Daemon (C++)
zmq_endpoint = "tcp://192.168.0.6:5555"

# Broker MQTT (Mosquitto)
mqtt_broker = "192.168.0.6"

# Puerto para la API HTTP local y Health Check
http_port = 3000